name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # 소스코드의 테스트를 진행하는 Job
  test:
    # 이 JOB은 우분투 최신 LTS에서 실행된다.
    runs-on: ubuntu-latest
    # 이 JOB의 개발 단계
    steps:
      # 소스코드 가져오기
      - name: Checkout Source
        # 이미 만들어진 Actions을 쓸 경우 uses
        uses: actions/checkout@v4
      # JDK 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        # Actions에 전달할 인자들
        with:
          java-version: '21'
          distribution: 'temurin'
      # Gradle 설정하기
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      # Gradle Wrapper로 테스트 진행
      - name: Test with Gradle Wrapper
        # 그냥 실행하는 명령의 경우 run
        run: ./gradlew test